USE [master]
GO
/****** Object:  Database [DDSDA]    Script Date: 12/12/2023 2:34:36 PM ******/
CREATE DATABASE [DDSDA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DDSDA', SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DDSDA_log',  SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DDSDA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DDSDA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DDSDA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DDSDA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DDSDA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DDSDA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DDSDA] SET ARITHABORT OFF 
GO
ALTER DATABASE [DDSDA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DDSDA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DDSDA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DDSDA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DDSDA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DDSDA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DDSDA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DDSDA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DDSDA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DDSDA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DDSDA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DDSDA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DDSDA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DDSDA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DDSDA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DDSDA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DDSDA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DDSDA] SET RECOVERY FULL 
GO
ALTER DATABASE [DDSDA] SET  MULTI_USER 
GO
ALTER DATABASE [DDSDA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DDSDA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DDSDA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DDSDA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DDSDA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DDSDA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DDSDA', N'ON'
GO
ALTER DATABASE [DDSDA] SET QUERY_STORE = ON
GO
ALTER DATABASE [DDSDA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DDSDA]
GO
/****** Object:  Table [dbo].[Dim_Branch]    Script Date: 12/12/2023 2:34:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Branch](
	[Branch_SK] [int] NOT NULL,
	[Branch_NK] [nvarchar](5) NULL,
	[Name] [nvarchar](255) NULL,
	[Status] [int] NULL,
 CONSTRAINT [PK_Dim_Branch] PRIMARY KEY CLUSTERED 
(
	[Branch_SK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Customer]    Script Date: 12/12/2023 2:34:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Customer](
	[CustomerID_SK] [int] NOT NULL,
	[CustomerID_NK] [nvarchar](10) NULL,
	[Status] [int] NULL,
	[Gender] [nvarchar](6) NULL,
 CONSTRAINT [PK_Dim_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerID_SK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Date]    Script Date: 12/12/2023 2:34:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Date](
	[DateID] [int] NOT NULL,
	[Date] [date] NULL,
	[Day] [int] NULL,
	[Month] [int] NULL,
	[Year] [int] NULL,
 CONSTRAINT [PK_Dim_Date] PRIMARY KEY CLUSTERED 
(
	[DateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_PaymentMethod]    Script Date: 12/12/2023 2:34:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_PaymentMethod](
	[Payment_SK] [int] NOT NULL,
	[Payment_NK] [int] NULL,
	[PaymentType] [nvarchar](255) NULL,
	[Status] [int] NULL,
 CONSTRAINT [PK_Dim_PaymentMethod] PRIMARY KEY CLUSTERED 
(
	[Payment_SK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Product]    Script Date: 12/12/2023 2:34:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Product](
	[Product_SK] [int] NOT NULL,
	[Product_NK] [nvarchar](255) NULL,
	[Productline] [nvarchar](255) NULL,
	[UnitPrice] [money] NULL,
	[Source] [int] NULL,
	[Status] [int] NULL,
 CONSTRAINT [PK_Dim_Product] PRIMARY KEY CLUSTERED 
(
	[Product_SK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fact_Sale]    Script Date: 12/12/2023 2:34:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fact_Sale](
	[Sale_ID] [int] IDENTITY(1,1) NOT NULL,
	[DateID] [int] NULL,
	[Customer_SK] [int] NULL,
	[Product_SK] [int] NULL,
	[Branch_SK] [int] NULL,
	[Payment_ID] [int] NULL,
	[Quantity] [int] NULL,
	[UnitPrice] [money] NULL,
	[Rating] [int] NULL,
	[TotalRevenue] [money] NULL,
 CONSTRAINT [PK_Fact_Sale] PRIMARY KEY CLUSTERED 
(
	[Sale_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fact_Sale]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Sale_Dim_Branch] FOREIGN KEY([Branch_SK])
REFERENCES [dbo].[Dim_Branch] ([Branch_SK])
GO
ALTER TABLE [dbo].[Fact_Sale] CHECK CONSTRAINT [FK_Fact_Sale_Dim_Branch]
GO
ALTER TABLE [dbo].[Fact_Sale]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Sale_Dim_Customer] FOREIGN KEY([Customer_SK])
REFERENCES [dbo].[Dim_Customer] ([CustomerID_SK])
GO
ALTER TABLE [dbo].[Fact_Sale] CHECK CONSTRAINT [FK_Fact_Sale_Dim_Customer]
GO
ALTER TABLE [dbo].[Fact_Sale]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Sale_Dim_Date] FOREIGN KEY([DateID])
REFERENCES [dbo].[Dim_Date] ([DateID])
GO
ALTER TABLE [dbo].[Fact_Sale] CHECK CONSTRAINT [FK_Fact_Sale_Dim_Date]
GO
ALTER TABLE [dbo].[Fact_Sale]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Sale_Dim_PaymentMethod] FOREIGN KEY([Payment_ID])
REFERENCES [dbo].[Dim_PaymentMethod] ([Payment_SK])
GO
ALTER TABLE [dbo].[Fact_Sale] CHECK CONSTRAINT [FK_Fact_Sale_Dim_PaymentMethod]
GO
ALTER TABLE [dbo].[Fact_Sale]  WITH CHECK ADD  CONSTRAINT [FK_Fact_Sale_Dim_Product] FOREIGN KEY([Product_SK])
REFERENCES [dbo].[Dim_Product] ([Product_SK])
GO
ALTER TABLE [dbo].[Fact_Sale] CHECK CONSTRAINT [FK_Fact_Sale_Dim_Product]
GO
USE [master]
GO
ALTER DATABASE [DDSDA] SET  READ_WRITE 
GO
